openapi: '3.0.0'
info:
  title: Immage Galeery Neuron Nvntry
  version: '1.0'
servers:
  - url: http://localhost:3002/api/v1/
paths:
  /resource:
    get:
      responses:
        '200':
          description: OK
    post:
      description: 'to post a one or multiple image files'
      parameters: []
      responses:
        '200':
          description: OK
